### ISSUE TITLE
Information for the changes to softwaretesting conferences

### ISSUE THREAD

**Issue by nashvillewest** [TestingConferences/testingconferences.github.io#367]
Hi,

> IEEE International Conference on Software Testing, Verification and Validation (ICST) 2020
>  March 23-27, 2020  Porto, Portugal  Registration is Open

moved to October 24-28

> TAIC PART 2020
>  March 23, 2020  Porto, Portugal

moved to October 24

> InSTA 2020 - International Workshop on Software Test Architecture
>  March 27, 2020  Porto, Portugal

moved to October 28

> IEEE International Conference on AI Testing 2020
>  April 13-16, 2020  Oxford, UK

Postponed to Summer 2020

Best

**Comment by ckenst** [comment]
@nashvillewest thanks for this information!

**Comment by ckenst** [comment]
Included in the general list and in the blog post on conference changes
