### ISSUE TITLE
Software Testing and QA Conferences and Events in 2020

### ISSUE THREAD

**Issue by ligurio** [TestingConferences/testingconferences.github.io#370]
Please add conferences from a list https://docs.google.com/spreadsheets/d/1OSzBf7qotPBHIAisuCra9_AduzlVLOakHgjtjOUJ0wo/edit#gid=0

**Comment by ckenst** [comment]
@ligurio 

FWIW:
1. I've seen this list
2. Some of the list is out of date
3. We already have many of them
4. I found quite a few of them are [not eligible](https://github.com/TestingConferences/testingconferences.github.io#eligible-conferences-and-workshops) based on what we are focusing on. 

Is there a specific conference you think we are missing?

**Comment by ligurio** [comment]
Perfect! So we can close the issue.

**Comment by ckenst** [comment]
Thanks anyways!
