### ISSUE TITLE
Other Tech Conferences List

### ISSUE THREAD

**Issue by ckenst** [TestingConferences/testingconferences.github.io#394]
We have a list of other tech conferences (online tech conferences). Can we make this list more up to date:

1. https://www.katherinejohnsonsummit.com/
2. https://agiledevopseast.techwell.com/
3. https://www.hiddengemsconf.com/

**Comment by ckenst** [comment]
https://www.trajectoryconf.com

**Comment by Saket2** [comment]
Hello Testers,



TheTestTribe, India's Largest Software Testing Community is here with #TestFlix, one of a kind Global Software Testing Binge.



15 hours of binge-watch filled with 100 Atomic Talks by Speakers from over 40 countries.



Event URL: http://bit.ly/testflix

Register for FREE: https://lnkd.in/gSeF8Fy



Please support us by sharing this to all your fellow testers, don’t forget to use the hashtag #TestFlix while you spread the word on social media !

https://www.thetesttribe.com/testflix/#sec1

Thank you!

**Comment by ckenst** [comment]
@Saket2 it is not appropriate to spam our Issues list with advertisements.

**Comment by ckenst** [comment]
https://events.linuxfoundation.org/openapi-asc/
